// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2026 Antoni Romera

package controller

import (
	"fmt"
	"sort"
	"strings"

	doblurav1alpha1 "github.com/doblura/doblura/api/v1alpha1"
)

// greenmaskConfig generates greenmask's configuration YAML.
//
// Generated rather than asked of the user on purpose: hand-writing rules for
// seventy Odoo columns is where the mistakes that matter get made, and the
// resulting YAML ends up in an auditable ConfigMap.
// greenmaskOut is where greenmask puts what it produces, inside the pod's
// scratch volume. Named once and used by both the config and the script that
// collects the result: two places agreeing by coincidence is how the dump ends up
// somewhere nobody looks.
const greenmaskOut = "/scratch/greenmask"

func greenmaskConfig(s *doblurav1alpha1.OdooSnapshotSpec, dbName string) string {
	rules := s.RulesToApply()

	// Group by table: greenmask's format is a list of tables, each with its own
	// transformers.
	byTable := map[string][]doblurav1alpha1.MaskRule{}
	for _, r := range rules {
		byTable[r.Table] = append(byTable[r.Table], r)
	}
	tables := make([]string, 0, len(byTable))
	for t := range byTable {
		tables = append(tables, t)
	}
	// Stable ordering: without it the ConfigMap changes on every reconciliation
	// and triggers phantom rollouts.
	sort.Strings(tables)

	var b strings.Builder
	b.WriteString("# Generated by Doblura. Do not edit: regenerated on every reconciliation.\n")
	b.WriteString("common:\n")
	// No pg_bin_path. It used to be pinned to /usr/lib/postgresql/16/bin, which is
	// wrong the moment the image ships a different major — and the Odoo 19 image
	// ships the 18 client, in /usr/bin. Hardcoding a version here is the same
	// footgun that already cost an afternoon on the client/server mismatch, so
	// greenmask finds the tools on PATH instead.
	b.WriteString("  tmp_dir: \"/tmp\"\n")
	// Where greenmask writes. Without it greenmask refuses to start:
	//
	//   directory storage config validation failed: path is required
	//
	// which arrives AFTER the pipeline has copied production, neutralized it and
	// masked it — the three expensive steps — and was never seen because nothing
	// had run the greenmask engine end to end. The config validator in
	// hack/verify-greenmask-config.sh stops at the connection error, and greenmask
	// checks its storage before it connects.
	// TOP LEVEL, not under common: greenmask answers `'common' has invalid keys:
	// storage`, which is the kind of thing only the tool itself will tell you.
	b.WriteString("storage:\n")
	b.WriteString("  type: \"directory\"\n")
	b.WriteString("  directory:\n")
	b.WriteString("    path: \"" + greenmaskOut + "\"\n")
	b.WriteString("dump:\n")
	b.WriteString("  pg_dump_options:\n")
	b.WriteString("    dbname: \"" + dbName + "\"\n")
	b.WriteString("    format: directory\n")

	// Table truncation: --exclude-table-data, NOT --exclude-table.
	//
	// It keeps the table, the schema, the indexes and the constraints, and omits
	// only the rows. With --exclude-table the restore leaves a schema Odoo's ORM
	// does not recognise and it will not start. That is the difference between
	// "you cannot skip tables in Odoo" and "yes you can".
	// A YAML LIST, not one key per table.
	//
	// pg_dump_options is a map, and a map cannot hold the same key twice: emitting
	// `exclude-table-data:` once per table produced a document where all but the
	// last were silently discarded, so exactly one table would have been
	// truncated. Printing the generated config is what caught it — the Go tests
	// only ever asserted that the string appeared.
	if tables := s.TablesToTruncate(); len(tables) > 0 {
		b.WriteString("    exclude-table-data:\n")
		for _, t := range tables {
			b.WriteString("      - \"public." + t + "\"\n")
		}
	}

	b.WriteString("  transformation:\n")

	// Subsetting goes on the TABLE entry, not at the dump level.
	//
	// The first attempt put `dump.subset_conds` as a top-level key and greenmask
	// rejected the config outright: "'dump' has invalid keys: subset_conds". The
	// condition belongs to the table it filters, and greenmask walks the
	// foreign-key graph outward from there.
	//
	// res_company is the root because everything company-scoped reaches it through
	// company_id — which is what turns "this customer's data" into something a
	// tool can actually compute.
	subsetRoot := ""
	if sub := s.Subset; sub != nil && len(sub.Companies) > 0 {
		subsetRoot = "res_company"
		quoted := make([]string, 0, len(sub.Companies))
		for _, c := range sub.Companies {
			quoted = append(quoted, "'"+strings.ReplaceAll(c, "'", "''")+"'")
		}
		b.WriteString("    - schema: \"public\"\n")
		b.WriteString("      name: \"res_company\"\n")
		b.WriteString("      subset_conds:\n")
		b.WriteString("        - \"res_company.name IN (" + strings.Join(quoted, ", ") + ")\"\n")
		if rules, ok := byTable[subsetRoot]; ok {
			b.WriteString("      transformers:\n")
			for _, r := range rules {
				b.WriteString(transformerYAML(r))
			}
		}
	}

	for _, t := range tables {
		if t == subsetRoot {
			continue // already emitted above, with its subset condition
		}
		b.WriteString("    - schema: \"public\"\n")
		b.WriteString("      name: \"" + t + "\"\n")
		b.WriteString("      transformers:\n")
		for _, r := range byTable[t] {
			b.WriteString(transformerYAML(r))
		}
	}
	return b.String()
}

// transformerYAML maps a MaskKind onto greenmask's concrete transformer.
//
// Every name and every parameter here was checked against the tool — `greenmask
// list-transformers` and `show-transformer` — because the previous version was
// checked against nothing. It named RandomStreetAddress, RandomCity and
// RandomZipCode, none of which exist; it passed `engine` to transformers that
// have no such parameter; and it gave RandomPerson a `column` when the parameter
// is `columns`. greenmask refused the whole dump, which is the correct behaviour
// and means the greenmask engine had never produced a single anonymized dump.
//
// The Go tests all passed throughout, because they asserted on substrings of a
// string. A substring is not a schema.
//
// DETERMINISM, which is the decision this file turns on: if the same customer
// comes out with a different name in every dump, QA cannot reproduce last week's
// bug report and two rehearsals cannot be compared.
//
// It is achievable for the columns where it matters most and not for all of them,
// and this is measured rather than assumed — each form below was run through
// `greenmask validate` against a real database:
//
//	deterministic: RandomPerson and RandomEmail (engine: hash), and Hash, which
//	               is deterministic by construction. Names, emails, tax IDs and
//	               IBANs are what a person is correlated BY.
//	not:           RandomPhoneNumber, RandomSentence, RandomURL and RealAddress
//	               have no engine parameter in greenmask v0.2.22, so a phone
//	               number or a city changes between two dumps of the same row.
//
// The gap is worth knowing about and is not worth closing by hashing those
// columns instead: a hash in a city field is not a city, and the point of this
// pipeline is realistic data.
func transformerYAML(r doblurav1alpha1.MaskRule) string {
	ind := "        "
	// one column, one transformer, deterministic where the transformer allows it
	det := func(name, extra string) string {
		return ind + "- name: \"" + name + "\"\n" +
			ind + "  params:\n" +
			ind + "    column: \"" + r.Column + "\"\n" +
			ind + "    engine: \"hash\"\n" + extra
	}
	// and the same without an engine, for the ones that have no such parameter
	plain := func(name, extra string) string {
		return ind + "- name: \"" + name + "\"\n" +
			ind + "  params:\n" +
			ind + "    column: \"" + r.Column + "\"\n" + extra
	}
	// RandomPerson and RealAddress take `columns`: a list of column names each
	// with a go template over the generated record. One entry, because a MaskRule
	// is one column — the shape allows filling several columns from one generated
	// person, which is worth having later and is not what the CRD expresses today.
	templated := func(name, tpl, engine string) string {
		return ind + "- name: \"" + name + "\"\n" +
			ind + "  params:\n" +
			ind + "    columns:\n" +
			ind + "      - name: \"" + r.Column + "\"\n" +
			ind + "        template: \"" + tpl + "\"\n" + engine
	}
	hashEngine := ind + "    engine: \"hash\"\n"

	switch r.Kind {
	case doblurav1alpha1.MaskName:
		return templated("RandomPerson", "{{ .FirstName }} {{ .LastName }}", hashEngine)
	case doblurav1alpha1.MaskFirstName:
		return templated("RandomPerson", "{{ .FirstName }}", hashEngine)
	case doblurav1alpha1.MaskLastName:
		return templated("RandomPerson", "{{ .LastName }}", hashEngine)
	case doblurav1alpha1.MaskEmail:
		// keep_original_domain false: keeping the domain, four addresses from a
		// small company already tell you whose database this is.
		return det("RandomEmail", ind+"    keep_original_domain: false\n")
	case doblurav1alpha1.MaskPhone:
		// No engine parameter on this one, measured against greenmask v0.2.22.
		return plain("RandomPhoneNumber", "")
	case doblurav1alpha1.MaskAddress:
		return templated("RealAddress", "{{ .Address }}", "")
	case doblurav1alpha1.MaskCity:
		return templated("RealAddress", "{{ .City }}", "")
	case doblurav1alpha1.MaskZip:
		return templated("RealAddress", "{{ .PostalCode }}", "")
	case doblurav1alpha1.MaskVAT:
		// There is no tax-ID transformer, and a length-bounded hash does not
		// pretend to be a valid one, which is also the right behaviour. Hash takes
		// no engine: it is deterministic by construction.
		return plain("Hash", ind+"    function: \"sha1\"\n"+ind+"    max_length: 16\n")
	case doblurav1alpha1.MaskIBAN:
		return plain("Hash", ind+"    function: \"sha1\"\n"+ind+"    max_length: 24\n")
	case doblurav1alpha1.MaskURL:
		return plain("RandomURL", "")
	case doblurav1alpha1.MaskText:
		// Nor this one.
		return plain("RandomSentence", "")
	case doblurav1alpha1.MaskHash:
		return plain("Hash", ind+"    function: \"sha1\"\n")
	case doblurav1alpha1.MaskNull:
		// Emptying a column has nothing random about it.
		return plain("SetNull", "")
	case doblurav1alpha1.MaskFixed:
		return plain("Replace", ind+"    value: \""+r.Value+"\"\n")
	}
	return ""
}

// sqlMaskScript is the alternative engine: plain UPDATEs.
//
// No third-party dependencies, for when policy forbids new binaries. Slower and
// with less variety of fake data, but deterministic too: md5 of the original
// value plus a seed.
func sqlMaskScript(s *doblurav1alpha1.OdooSnapshotSpec, dbName string) string {
	var b strings.Builder
	b.WriteString("psql -v ON_ERROR_STOP=1 -d \"" + dbName + "\" <<'SQL'\nBEGIN;\n")

	for _, r := range s.RulesToApply() {
		b.WriteString(sqlForRule(r))
	}
	if s.Mask.ResetPasswords == nil || *s.Mask.ResetPasswords {
		b.WriteString(resetPasswordsSQL())
	}
	b.WriteString("COMMIT;\nSQL\n")
	return b.String()
}

func sqlForRule(r doblurav1alpha1.MaskRule) string {
	col, tbl := r.Column, r.Table
	// Deterministic: the same input yields the same output, so duplicates stay
	// duplicates and joins keep behaving the same way.
	h := fmt.Sprintf("md5(%s::text || 'doblura')", col)

	// The replacement values are chosen to be unreachable, not merely different.
	// Somebody reads a masked contact and tries it, so:
	//
	//   .invalid   is reserved by RFC 2606 and can never resolve.
	//   +999       is an ITU-unassigned country code, so it cannot be dialled.
	//              A plausible-looking national freephone prefix can be, which
	//              is the whole problem with masking data to something realistic.
	//
	// And every literal is English, because these strings end up in the data
	// support and QA actually look at — they are product copy, not internals.
	var expr string
	switch r.Kind {
	case doblurav1alpha1.MaskEmail:
		expr = fmt.Sprintf("'user-' || left(%s, 8) || '@example.invalid'", h)
	case doblurav1alpha1.MaskName, doblurav1alpha1.MaskFirstName, doblurav1alpha1.MaskLastName:
		expr = fmt.Sprintf("'Contact ' || left(%s, 8)", h)
	case doblurav1alpha1.MaskPhone:
		expr = fmt.Sprintf("'+999 ' || left(%s, 6)", h)
	case doblurav1alpha1.MaskAddress:
		expr = fmt.Sprintf("'Street ' || left(%s, 8)", h)
	case doblurav1alpha1.MaskCity:
		expr = fmt.Sprintf("'City ' || left(%s, 6)", h)
	case doblurav1alpha1.MaskZip:
		expr = fmt.Sprintf("left(%s, 5)", h)
	case doblurav1alpha1.MaskURL:
		expr = fmt.Sprintf("'https://example.invalid/' || left(%s, 8)", h)
	case doblurav1alpha1.MaskText:
		expr = "'anonymized text'"
	case doblurav1alpha1.MaskNull:
		expr = "NULL"
	case doblurav1alpha1.MaskFixed:
		expr = "'" + strings.ReplaceAll(r.Value, "'", "''") + "'"
	default: // Hash, VAT, IBAN
		expr = h
	}

	// The WHERE avoids rewriting rows that are already NULL: on large tables
	// that is the difference between minutes and hours, and it keeps the WAL
	// from ballooning.
	where := ""
	if r.Kind != doblurav1alpha1.MaskNull {
		where = fmt.Sprintf(" WHERE %s IS NOT NULL", col)
	}
	return fmt.Sprintf("UPDATE %s SET %s = %s%s;\n", tbl, col, expr, where)
}

// resetPasswordsSQL assigns the same known password to everyone.
//
// Known rather than random: an environment nobody can log into is useless for
// validating anything, and the risk is bounded by the network, not by an
// impossible password. Odoo recomputes the hash on startup when the field does
// not look like a valid hash, so leaving the plaintext and forcing a rehash is
// enough.
func resetPasswordsSQL() string {
	return "-- Known password for everyone: an unreachable environment cannot be validated.\n" +
		"UPDATE res_users SET password = '" + doblurav1alpha1.PasswordResetValue + "';\n"
}

// neutralizeScript cuts the outbound paths BEFORE cleaning anything.
//
// The order matters: if the pod dies halfway through the pipeline, the work
// database must not sit for even a second with production mail servers
// configured and reachable. Cut first, clean afterwards.
func neutralizeScript(dbName, confPath string) string {
	return fmt.Sprintf(`echo ">> neutralizing %[1]s BEFORE touching the data"
# Odoo's native command (v16+): disables scheduled actions, outgoing mail,
# payment providers and delivery carriers. Every module can ship its own
# data/neutralize.sql, so this covers third-party addons too.
# The subcommand comes FIRST. With -c first, Odoo takes the default "server"
# command and dies on "neutralize" as a stray positional -- which is what this
# line did on every image, while reading as if it worked. The belt-and-braces
# below then covered mail and crons, and nothing covered payment providers.
odoo neutralize -c %[2]s -d "%[1]s"

# Belt and braces: if the image predates v16 or the command fails, the bare
# minimum by hand. This being idempotent is deliberate.
psql -v ON_ERROR_STOP=1 -d "%[1]s" <<'SQL'
BEGIN;
UPDATE ir_mail_server SET active = false;
UPDATE ir_cron SET active = false;
COMMIT;
SQL

# fetchmail is a module and may not be installed, and the two obvious guards both
# fail here. A WHERE clause does not help: Postgres resolves the relation while
# PARSING the statement, so a missing table is an error before the WHERE runs. And
# a dollar-quoted DO block does not survive the trip: this script reaches the
# container as an ARGUMENT, where Kubernetes rewrites $$ into a single $ — the
# block arrived as "DO $ BEGIN" and psql reported a syntax error at a character
# nobody wrote.
#
# So psql decides. The UPDATE is a STRING until \gexec runs it, and \gexec runs
# nothing when the SELECT returns no rows.
psql -v ON_ERROR_STOP=1 -d "%[1]s" <<'SQL'
SELECT 'UPDATE fetchmail_server SET active = false'
WHERE to_regclass('fetchmail_server') IS NOT NULL
\gexec
SQL
echo ">> neutralized"`, dbName, confPath)
}
