// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2026 Antoni Romera

package controller

import (
	"fmt"
	"strings"

	doblurav1alpha1 "github.com/doblura/doblura/api/v1alpha1"
)

// phaseScript returns the shell for each phase.
//
// It is generated by the operator rather than baked into the image so the
// contract with the user's image stays minimal: all it needs is
// click-odoo-contrib. There is no Doblura base image to adopt.
func phaseScript(reh *doblurav1alpha1.OdooRehearsal, st *doblurav1alpha1.OdooRehearsalStatus) string {
	switch st.Phase {
	case doblurav1alpha1.PhaseRestoring:
		return restoreScript(reh, st)
	case doblurav1alpha1.PhaseMigrating:
		return migrateScript(reh, st)
	case doblurav1alpha1.PhaseAsserting:
		return assertScript(reh, st)
	}
	return "echo 'unknown phase' >&2; exit 1"
}

func restoreScript(reh *doblurav1alpha1.OdooRehearsal, st *doblurav1alpha1.OdooRehearsalStatus) string {
	// The command depends on the FORMAT, not the provider. By the time we get
	// here the dump is already at /snapshot and it makes no difference whether
	// rclone, curl, your own container or an already-mounted PVC brought it.
	// The version banner is not decoration. A Postgres client newer than the
	// server emits SQL the server rejects — a pg18 pg_dump writes
	// `SET transaction_timeout`, which PG16 does not know — and the tools report
	// it as a bare "Couldn't restore database". Printing both versions first
	// turns twenty minutes of confusion into one line of log.
	format := orDefault(string(reh.Spec.Snapshot.Format), string(doblurav1alpha1.FormatOdooBackup))
	source, stage := doblurav1alpha1.SnapshotMountPath, ""

	// OdooBackup needs the dump staged into a writable directory first.
	//
	// click-odoo-restoredb does shutil.move() on the filestore: it MOVES it out
	// of the source folder into data_dir. Doblura mounts the snapshot ReadOnly on
	// purpose, so that one rehearsal cannot damage the dump the next ones and
	// every test environment depend on — and a moving restore is flatly
	// incompatible with that.
	//
	// Copying costs disk and time, and it is the right trade: the alternative is
	// a writable shared dump that the first rehearsal quietly dismantles. The
	// scratch copy dies with the pod.
	//
	// pg_restore and psql only read, so PgDump and PgPlain restore in place.
	if format == string(doblurav1alpha1.FormatOdooBackup) {
		source = doblurav1alpha1.StagePath + "/dump"
		stage = fmt.Sprintf(`echo ">> staging the dump into a writable copy (restoredb moves the filestore)"
mkdir -p %[1]s
cp -a %[2]s %[1]s/dump
`, doblurav1alpha1.StagePath, doblurav1alpha1.SnapshotMountPath)
	}

	return fmt.Sprintf(`echo ">> restoring %s into %s (format %s)"
echo ">> pg client: $(pg_restore --version 2>/dev/null || echo unknown)"
echo ">> pg server: $(psql -d postgres -tAc 'show server_version' 2>/dev/null || echo unreachable)"
%s%s
echo ">> restore finished"`,
		source, st.DatabaseName, format,
		stage,
		reh.Spec.Snapshot.RestoreCommand(st.DatabaseName, confPath, source))
}

// confPath is where the operator mounts the odoo.conf it composes.
const confPath = "/etc/doblura/odoo.conf"

func orDefault(v, def string) string {
	if v == "" {
		return def
	}
	return v
}

func migrateScript(reh *doblurav1alpha1.OdooRehearsal, st *doblurav1alpha1.OdooRehearsalStatus) string {
	var cmd string
	switch reh.Spec.Migration.Engine {
	case doblurav1alpha1.EngineOdooUpdateAll:
		cmd = fmt.Sprintf(`odoo -c /etc/doblura/odoo.conf -d "%s" -u all --stop-after-init`, st.DatabaseName)
	case doblurav1alpha1.EngineMarabunta:
		cmd = fmt.Sprintf(`MARABUNTA_DATABASE="%s" MARABUNTA_MODE=full marabunta`, st.DatabaseName)
	default: // ClickOdooUpdate
		cmd = fmt.Sprintf(`click-odoo-update -c /etc/doblura/odoo.conf -d "%s"`, st.DatabaseName)
		if len(reh.Spec.Migration.Modules) > 0 {
			cmd += " --i18n-overwrite"
		}
	}
	if extra := reh.Spec.Migration.ExtraArgs; len(extra) > 0 {
		cmd += " " + strings.Join(extra, " ")
	}
	// The controller times this from the Job's timestamps, not from this script:
	// that way the measurement includes pod startup, which also counts against
	// your real maintenance window.
	return fmt.Sprintf(`echo ">> migrating %s"
%s
echo ">> migration finished"`, st.DatabaseName, cmd)
}

func assertScript(reh *doblurav1alpha1.OdooRehearsal, st *doblurav1alpha1.OdooRehearsalStatus) string {
	if len(reh.Spec.Assertions.ModelCounts) == 0 {
		return `echo ">> no assertions declared"`
	}
	var py strings.Builder
	py.WriteString("failed = []\n")
	for _, a := range reh.Spec.Assertions.ModelCounts {
		py.WriteString(fmt.Sprintf(
			"n = env['%s'].search_count([])\n"+
				"print('%s: %%d' %% n)\n"+
				"if n < %d: failed.append('%s: %%d < %d' %% n)\n",
			a.Model, a.Model, a.MinCount, a.Model, a.MinCount))
	}
	py.WriteString("env.cr.rollback()\n")
	py.WriteString("if failed:\n    raise SystemExit('aserciones fallidas: ' + '; '.join(failed))\n")

	// The script goes to a file and click-odoo gets the path.
	//
	// NOT `click-odoo ... -` : click-odoo validates SCRIPT as an existing file
	// and rejects "-" outright ("File '-' does not exist"). Piping to stdin does
	// work, but a file is better here: when an assertion fails you can exec into
	// the pod and read the exact script that ran.
	return fmt.Sprintf(`echo ">> checking critical models"
cat > /tmp/doblura-assert.py <<'PYSCRIPT'
%s
PYSCRIPT
click-odoo -c %s -d "%s" /tmp/doblura-assert.py`, py.String(), confPath, st.DatabaseName)
}
