#!/usr/bin/env python3
"""Copy every generated artifact into the chart.

Two things used to be hand-maintained copies of generated content, and both
diverged silently:

  * the CRDs — the chart only shipped OdooRehearsal, so a Helm install left the
    operator watching an OdooSnapshot kind that did not exist, and it
    crash-looped on cache sync.
  * the RBAC rules — the chart's ClusterRole was written by hand and never got
    the cronjobs and networkpolicies permissions the OdooSnapshot controller
    needs, so the informer could not list them.

Both were found by the first real end-to-end run and neither was visible to any
unit test. Generating them is the only fix that stays fixed.
"""
import pathlib
import yaml

CRD_DIR = pathlib.Path("config/crd")
WEBHOOK_MANIFEST = pathlib.Path("config/webhook/manifests.yaml")
TPL_DIR = pathlib.Path("charts/doblura/templates")


def flow(value):
    """Render a list the way the rest of the chart writes them: on one line."""
    return yaml.dump(value, default_flow_style=True).strip()

KEEP_NOTE = (
    "  annotations:\n"
    "    # keep: a `helm uninstall` must NOT take everyone's Doblura objects down\n"
    "    # with it. Deleting a CRD deletes every object of that kind.\n"
    "    helm.sh/resource-policy: keep"
)
HEADER = (
    "{{- if .Values.crds.install }}\n"
    "# Generated by controller-gen and copied by hack/sync-chart.py.\n"
    "# Do NOT edit by hand: `make chart-sync` regenerates it.\n"
    "#\n"
    "# It lives in templates/ rather than crds/ on purpose: the ones in crds/ are\n"
    "# only installed the first time and `helm upgrade` never updates them.\n"
)

# ── CRDs: all of them, one template each ──
for old in TPL_DIR.glob("crd-*.yaml"):
    old.unlink()

crds = sorted(CRD_DIR.glob("*.yaml"))
for src in crds:
    doc = yaml.safe_load(src.read_text())
    kind = doc["spec"]["names"]["kind"].lower()
    body = src.read_text().replace(
        f"  name: {doc['metadata']['name']}",
        f"  name: {doc['metadata']['name']}\n{KEEP_NOTE}",
        1,
    )
    (TPL_DIR / f"crd-{kind}.yaml").write_text(HEADER + body + "{{- end }}\n")
    print(f"  CRD  {kind}")

# ── RBAC: the rules come from controller-gen ──
rules = yaml.safe_load(pathlib.Path("config/rbac/role.yaml").read_text())["rules"]
lines = []
for r in rules:
    lines.append("  - apiGroups: " + yaml.dump(r.get("apiGroups", []), default_flow_style=True).strip())
    lines.append("    resources: " + yaml.dump(r.get("resources", []), default_flow_style=True).strip())
    lines.append("    verbs: " + yaml.dump(r.get("verbs", []), default_flow_style=True).strip())
rules_block = "\n".join(lines)

rbac = TPL_DIR / "rbac.yaml"
text = rbac.read_text()
start = text.index("rules:\n") + len("rules:\n")
end = text.index("---", start)
generated = (
    "  # Generated from config/rbac/role.yaml by hack/sync-chart.py.\n"
    "  # Do NOT edit by hand: the markers in internal/controller are the source.\n"
    "  #\n"
    "  # Note on secrets: the operator READS git and object-store credentials and\n"
    "  # WRITES the ephemeral GitHub App installation token. It is the most\n"
    "  # sensitive permission here; if your policy forbids it cluster-wide, set\n"
    "  # watchNamespaces and swap this ClusterRole for per-namespace Roles.\n"
    + rules_block + "\n"
)
rbac.write_text(text[:start] + generated + text[end:])
print(f"  RBAC {len(rules)} rules from controller-gen")

# ── Webhooks: the rules, failurePolicy and paths come from the markers ──
#
# The third thing that must not be hand-copied. The path a webhook is served on is
# a string in a Go marker and a string in this manifest, and if they disagree the
# API server calls a route that does not exist — which, with failurePolicy Fail,
# means every OdooEnvironment create is refused. Nothing else in the system would
# say why.
#
# The clientConfig is NOT taken from the generated manifest: the Service name and
# namespace depend on the release, so they are written as Helm expressions here.
# Everything that describes WHAT is intercepted comes from controller-gen.
docs = [d for d in yaml.safe_load_all(WEBHOOK_MANIFEST.read_text()) if d]
webhook_tpl = TPL_DIR / "webhook.yaml"
text = webhook_tpl.read_text()

for doc in docs:
    kind = "mutating" if doc["kind"].startswith("Mutating") else "validating"
    lines = []
    for wh in doc["webhooks"]:
        lines.append(f"  - name: {wh['name']}")
        lines.append("    clientConfig:")
        lines.append("      service:")
        lines.append('        name: {{ include "doblura.fullname" . }}-webhook')
        lines.append("        namespace: {{ .Release.Namespace }}")
        lines.append(f"        path: {wh['clientConfig']['service']['path']}")
        lines.append("        port: 443")
        for field in ("failurePolicy", "matchPolicy", "sideEffects", "timeoutSeconds",
                      "reinvocationPolicy"):
            if field in wh:
                lines.append(f"    {field}: {wh[field]}")
        lines.append("    admissionReviewVersions: " + flow(wh["admissionReviewVersions"]))
        lines.append("    rules:")
        for r in wh["rules"]:
            lines.append("      - apiGroups: " + flow(r["apiGroups"]))
            lines.append("        apiVersions: " + flow(r["apiVersions"]))
            lines.append("        operations: " + flow(r["operations"]))
            lines.append("        resources: " + flow(r["resources"]))
            if "scope" in r:
                lines.append(f"        scope: {r['scope']}")

    begin = f"  # doblura:webhooks-begin {kind}\n"
    end = f"  # doblura:webhooks-end {kind}"
    if begin not in text or end not in text:
        raise SystemExit(f"charts/doblura/templates/webhook.yaml has no {kind} markers")
    head, rest = text.split(begin, 1)
    _, tail = rest.split(end, 1)
    text = head + begin + "\n".join(lines) + "\n" + end + tail
    print(f"  WH   {kind}: {len(doc['webhooks'])} webhook(s) from controller-gen")

webhook_tpl.write_text(text)
