#!/usr/bin/env python3
"""Copy every generated artifact into the chart.

Two things used to be hand-maintained copies of generated content, and both
diverged silently:

  * the CRDs — the chart only shipped OdooRehearsal, so a Helm install left the
    operator watching an OdooSnapshot kind that did not exist, and it
    crash-looped on cache sync.
  * the RBAC rules — the chart's ClusterRole was written by hand and never got
    the cronjobs and networkpolicies permissions the OdooSnapshot controller
    needs, so the informer could not list them.

Both were found by the first real end-to-end run and neither was visible to any
unit test. Generating them is the only fix that stays fixed.
"""
import pathlib
import yaml

CRD_DIR = pathlib.Path("config/crd")
TPL_DIR = pathlib.Path("charts/doblura/templates")

KEEP_NOTE = (
    "  annotations:\n"
    "    # keep: a `helm uninstall` must NOT take everyone's Doblura objects down\n"
    "    # with it. Deleting a CRD deletes every object of that kind.\n"
    "    helm.sh/resource-policy: keep"
)
HEADER = (
    "{{- if .Values.crds.install }}\n"
    "# Generated by controller-gen and copied by hack/sync-chart.py.\n"
    "# Do NOT edit by hand: `make chart-sync` regenerates it.\n"
    "#\n"
    "# It lives in templates/ rather than crds/ on purpose: the ones in crds/ are\n"
    "# only installed the first time and `helm upgrade` never updates them.\n"
)

# ── CRDs: all of them, one template each ──
for old in TPL_DIR.glob("crd-*.yaml"):
    old.unlink()

crds = sorted(CRD_DIR.glob("*.yaml"))
for src in crds:
    doc = yaml.safe_load(src.read_text())
    kind = doc["spec"]["names"]["kind"].lower()
    body = src.read_text().replace(
        f"  name: {doc['metadata']['name']}",
        f"  name: {doc['metadata']['name']}\n{KEEP_NOTE}",
        1,
    )
    (TPL_DIR / f"crd-{kind}.yaml").write_text(HEADER + body + "{{- end }}\n")
    print(f"  CRD  {kind}")

# ── RBAC: the rules come from controller-gen ──
rules = yaml.safe_load(pathlib.Path("config/rbac/role.yaml").read_text())["rules"]
lines = []
for r in rules:
    lines.append("  - apiGroups: " + yaml.dump(r.get("apiGroups", []), default_flow_style=True).strip())
    lines.append("    resources: " + yaml.dump(r.get("resources", []), default_flow_style=True).strip())
    lines.append("    verbs: " + yaml.dump(r.get("verbs", []), default_flow_style=True).strip())
rules_block = "\n".join(lines)

rbac = TPL_DIR / "rbac.yaml"
text = rbac.read_text()
start = text.index("rules:\n") + len("rules:\n")
end = text.index("---", start)
generated = (
    "  # Generated from config/rbac/role.yaml by hack/sync-chart.py.\n"
    "  # Do NOT edit by hand: the markers in internal/controller are the source.\n"
    "  #\n"
    "  # Note on secrets: the operator READS git and object-store credentials and\n"
    "  # WRITES the ephemeral GitHub App installation token. It is the most\n"
    "  # sensitive permission here; if your policy forbids it cluster-wide, set\n"
    "  # watchNamespaces and swap this ClusterRole for per-namespace Roles.\n"
    + rules_block + "\n"
)
rbac.write_text(text[:start] + generated + text[end:])
print(f"  RBAC {len(rules)} rules from controller-gen")
