//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AddonRepo) DeepCopyInto(out *AddonRepo) {
	*out = *in
	if in.Paths != nil {
		in, out := &in.Paths, &out.Paths
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Auth != nil {
		in, out := &in.Auth, &out.Auth
		*out = new(GitAuth)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AddonRepo.
func (in *AddonRepo) DeepCopy() *AddonRepo {
	if in == nil {
		return nil
	}
	out := new(AddonRepo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AddonVolume) DeepCopyInto(out *AddonVolume) {
	*out = *in
	if in.Paths != nil {
		in, out := &in.Paths, &out.Paths
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AddonVolume.
func (in *AddonVolume) DeepCopy() *AddonVolume {
	if in == nil {
		return nil
	}
	out := new(AddonVolume)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AddonsSpec) DeepCopyInto(out *AddonsSpec) {
	*out = *in
	if in.Baked != nil {
		in, out := &in.Baked, &out.Baked
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Repos != nil {
		in, out := &in.Repos, &out.Repos
		*out = make([]AddonRepo, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Volume != nil {
		in, out := &in.Volume, &out.Volume
		*out = new(AddonVolume)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AddonsSpec.
func (in *AddonsSpec) DeepCopy() *AddonsSpec {
	if in == nil {
		return nil
	}
	out := new(AddonsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Assertions) DeepCopyInto(out *Assertions) {
	*out = *in
	if in.ModelCounts != nil {
		in, out := &in.ModelCounts, &out.ModelCounts
		*out = make([]ModelCountAssertion, len(*in))
		copy(*out, *in)
	}
	if in.Custom != nil {
		in, out := &in.Custom, &out.Custom
		*out = new(CustomAssertion)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Assertions.
func (in *Assertions) DeepCopy() *Assertions {
	if in == nil {
		return nil
	}
	out := new(Assertions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Budget) DeepCopyInto(out *Budget) {
	*out = *in
	if in.MaxUpgradeDuration != nil {
		in, out := &in.MaxUpgradeDuration, &out.MaxUpgradeDuration
		*out = new(v1.Duration)
		**out = **in
	}
	if in.HardTimeout != nil {
		in, out := &in.HardTimeout, &out.HardTimeout
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Budget.
func (in *Budget) DeepCopy() *Budget {
	if in == nil {
		return nil
	}
	out := new(Budget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomAssertion) DeepCopyInto(out *CustomAssertion) {
	*out = *in
	if in.Command != nil {
		in, out := &in.Command, &out.Command
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Args != nil {
		in, out := &in.Args, &out.Args
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomAssertion.
func (in *CustomAssertion) DeepCopy() *CustomAssertion {
	if in == nil {
		return nil
	}
	out := new(CustomAssertion)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomProvider) DeepCopyInto(out *CustomProvider) {
	*out = *in
	if in.Command != nil {
		in, out := &in.Command, &out.Command
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Args != nil {
		in, out := &in.Args, &out.Args
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.EnvFromSecrets != nil {
		in, out := &in.EnvFromSecrets, &out.EnvFromSecrets
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ExtraVolumeClaims != nil {
		in, out := &in.ExtraVolumeClaims, &out.ExtraVolumeClaims
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomProvider.
func (in *CustomProvider) DeepCopy() *CustomProvider {
	if in == nil {
		return nil
	}
	out := new(CustomProvider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatabaseSpec) DeepCopyInto(out *DatabaseSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatabaseSpec.
func (in *DatabaseSpec) DeepCopy() *DatabaseSpec {
	if in == nil {
		return nil
	}
	out := new(DatabaseSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnvAuth) DeepCopyInto(out *EnvAuth) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnvAuth.
func (in *EnvAuth) DeepCopy() *EnvAuth {
	if in == nil {
		return nil
	}
	out := new(EnvAuth)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnvData) DeepCopyInto(out *EnvData) {
	*out = *in
	if in.Snapshot != nil {
		in, out := &in.Snapshot, &out.Snapshot
		*out = new(SnapshotSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnvData.
func (in *EnvData) DeepCopy() *EnvData {
	if in == nil {
		return nil
	}
	out := new(EnvData)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnvExposure) DeepCopyInto(out *EnvExposure) {
	*out = *in
	if in.Public != nil {
		in, out := &in.Public, &out.Public
		*out = new(bool)
		**out = **in
	}
	out.Auth = in.Auth
	if in.NoIndex != nil {
		in, out := &in.NoIndex, &out.NoIndex
		*out = new(bool)
		**out = **in
	}
	if in.RateLimitRPS != nil {
		in, out := &in.RateLimitRPS, &out.RateLimitRPS
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnvExposure.
func (in *EnvExposure) DeepCopy() *EnvExposure {
	if in == nil {
		return nil
	}
	out := new(EnvExposure)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnvLifecycle) DeepCopyInto(out *EnvLifecycle) {
	*out = *in
	if in.TTL != nil {
		in, out := &in.TTL, &out.TTL
		*out = new(v1.Duration)
		**out = **in
	}
	if in.IdleTimeout != nil {
		in, out := &in.IdleTimeout, &out.IdleTimeout
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnvLifecycle.
func (in *EnvLifecycle) DeepCopy() *EnvLifecycle {
	if in == nil {
		return nil
	}
	out := new(EnvLifecycle)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnvSecurity) DeepCopyInto(out *EnvSecurity) {
	*out = *in
	if in.RandomizeUserPasswords != nil {
		in, out := &in.RandomizeUserPasswords, &out.RandomizeUserPasswords
		*out = new(bool)
		**out = **in
	}
	if in.AdminUsers != nil {
		in, out := &in.AdminUsers, &out.AdminUsers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.DenyEgress != nil {
		in, out := &in.DenyEgress, &out.DenyEgress
		*out = new(bool)
		**out = **in
	}
	if in.StripExternalCredentials != nil {
		in, out := &in.StripExternalCredentials, &out.StripExternalCredentials
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnvSecurity.
func (in *EnvSecurity) DeepCopy() *EnvSecurity {
	if in == nil {
		return nil
	}
	out := new(EnvSecurity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ErrNoInstance) DeepCopyInto(out *ErrNoInstance) {
	*out = *in
	if in.Rejected != nil {
		in, out := &in.Rejected, &out.Rejected
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ErrNoInstance.
func (in *ErrNoInstance) DeepCopy() *ErrNoInstance {
	if in == nil {
		return nil
	}
	out := new(ErrNoInstance)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitAuth) DeepCopyInto(out *GitAuth) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitAuth.
func (in *GitAuth) DeepCopy() *GitAuth {
	if in == nil {
		return nil
	}
	out := new(GitAuth)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HTTPProvider) DeepCopyInto(out *HTTPProvider) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HTTPProvider.
func (in *HTTPProvider) DeepCopy() *HTTPProvider {
	if in == nil {
		return nil
	}
	out := new(HTTPProvider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstanceCapacity) DeepCopyInto(out *InstanceCapacity) {
	*out = *in
	if in.ReservedGi != nil {
		in, out := &in.ReservedGi, &out.ReservedGi
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstanceCapacity.
func (in *InstanceCapacity) DeepCopy() *InstanceCapacity {
	if in == nil {
		return nil
	}
	out := new(InstanceCapacity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaskRule) DeepCopyInto(out *MaskRule) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MaskRule.
func (in *MaskRule) DeepCopy() *MaskRule {
	if in == nil {
		return nil
	}
	out := new(MaskRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaskRulePreset) DeepCopyInto(out *MaskRulePreset) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MaskRulePreset.
func (in *MaskRulePreset) DeepCopy() *MaskRulePreset {
	if in == nil {
		return nil
	}
	out := new(MaskRulePreset)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaskSpec) DeepCopyInto(out *MaskSpec) {
	*out = *in
	if in.Preset != nil {
		in, out := &in.Preset, &out.Preset
		*out = new(bool)
		**out = **in
	}
	if in.Rules != nil {
		in, out := &in.Rules, &out.Rules
		*out = make([]MaskRule, len(*in))
		copy(*out, *in)
	}
	if in.ResetPasswords != nil {
		in, out := &in.ResetPasswords, &out.ResetPasswords
		*out = new(bool)
		**out = **in
	}
	if in.MaskUserLogins != nil {
		in, out := &in.MaskUserLogins, &out.MaskUserLogins
		*out = new(bool)
		**out = **in
	}
	if in.CustomCommand != nil {
		in, out := &in.CustomCommand, &out.CustomCommand
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MaskSpec.
func (in *MaskSpec) DeepCopy() *MaskSpec {
	if in == nil {
		return nil
	}
	out := new(MaskSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MigrationSpec) DeepCopyInto(out *MigrationSpec) {
	*out = *in
	if in.Modules != nil {
		in, out := &in.Modules, &out.Modules
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ExtraArgs != nil {
		in, out := &in.ExtraArgs, &out.ExtraArgs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MigrationSpec.
func (in *MigrationSpec) DeepCopy() *MigrationSpec {
	if in == nil {
		return nil
	}
	out := new(MigrationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelCountAssertion) DeepCopyInto(out *ModelCountAssertion) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelCountAssertion.
func (in *ModelCountAssertion) DeepCopy() *ModelCountAssertion {
	if in == nil {
		return nil
	}
	out := new(ModelCountAssertion)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelCountResult) DeepCopyInto(out *ModelCountResult) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelCountResult.
func (in *ModelCountResult) DeepCopy() *ModelCountResult {
	if in == nil {
		return nil
	}
	out := new(ModelCountResult)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObjectStoreProvider) DeepCopyInto(out *ObjectStoreProvider) {
	*out = *in
	if in.ForcePathStyle != nil {
		in, out := &in.ForcePathStyle, &out.ForcePathStyle
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObjectStoreProvider.
func (in *ObjectStoreProvider) DeepCopy() *ObjectStoreProvider {
	if in == nil {
		return nil
	}
	out := new(ObjectStoreProvider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OdooDatabase) DeepCopyInto(out *OdooDatabase) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OdooDatabase.
func (in *OdooDatabase) DeepCopy() *OdooDatabase {
	if in == nil {
		return nil
	}
	out := new(OdooDatabase)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OdooDatabase) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OdooDatabaseList) DeepCopyInto(out *OdooDatabaseList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OdooDatabase, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OdooDatabaseList.
func (in *OdooDatabaseList) DeepCopy() *OdooDatabaseList {
	if in == nil {
		return nil
	}
	out := new(OdooDatabaseList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OdooDatabaseList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OdooDatabaseSpec) DeepCopyInto(out *OdooDatabaseSpec) {
	*out = *in
	if in.Companies != nil {
		in, out := &in.Companies, &out.Companies
		*out = make([]TenantCompany, len(*in))
		copy(*out, *in)
	}
	if in.SizeGi != nil {
		in, out := &in.SizeGi, &out.SizeGi
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OdooDatabaseSpec.
func (in *OdooDatabaseSpec) DeepCopy() *OdooDatabaseSpec {
	if in == nil {
		return nil
	}
	out := new(OdooDatabaseSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OdooDatabaseStatus) DeepCopyInto(out *OdooDatabaseStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OdooDatabaseStatus.
func (in *OdooDatabaseStatus) DeepCopy() *OdooDatabaseStatus {
	if in == nil {
		return nil
	}
	out := new(OdooDatabaseStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OdooEnvironment) DeepCopyInto(out *OdooEnvironment) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OdooEnvironment.
func (in *OdooEnvironment) DeepCopy() *OdooEnvironment {
	if in == nil {
		return nil
	}
	out := new(OdooEnvironment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OdooEnvironment) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OdooEnvironmentList) DeepCopyInto(out *OdooEnvironmentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OdooEnvironment, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OdooEnvironmentList.
func (in *OdooEnvironmentList) DeepCopy() *OdooEnvironmentList {
	if in == nil {
		return nil
	}
	out := new(OdooEnvironmentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OdooEnvironmentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OdooEnvironmentSpec) DeepCopyInto(out *OdooEnvironmentSpec) {
	*out = *in
	in.Addons.DeepCopyInto(&out.Addons)
	in.Data.DeepCopyInto(&out.Data)
	in.Migration.DeepCopyInto(&out.Migration)
	in.Lifecycle.DeepCopyInto(&out.Lifecycle)
	in.Exposure.DeepCopyInto(&out.Exposure)
	in.Security.DeepCopyInto(&out.Security)
	out.Database = in.Database
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OdooEnvironmentSpec.
func (in *OdooEnvironmentSpec) DeepCopy() *OdooEnvironmentSpec {
	if in == nil {
		return nil
	}
	out := new(OdooEnvironmentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OdooEnvironmentStatus) DeepCopyInto(out *OdooEnvironmentStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ExpiresAt != nil {
		in, out := &in.ExpiresAt, &out.ExpiresAt
		*out = (*in).DeepCopy()
	}
	if in.LastRequestTime != nil {
		in, out := &in.LastRequestTime, &out.LastRequestTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OdooEnvironmentStatus.
func (in *OdooEnvironmentStatus) DeepCopy() *OdooEnvironmentStatus {
	if in == nil {
		return nil
	}
	out := new(OdooEnvironmentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OdooInstance) DeepCopyInto(out *OdooInstance) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OdooInstance.
func (in *OdooInstance) DeepCopy() *OdooInstance {
	if in == nil {
		return nil
	}
	out := new(OdooInstance)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OdooInstance) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OdooInstanceList) DeepCopyInto(out *OdooInstanceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OdooInstance, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OdooInstanceList.
func (in *OdooInstanceList) DeepCopy() *OdooInstanceList {
	if in == nil {
		return nil
	}
	out := new(OdooInstanceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OdooInstanceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OdooInstanceSpec) DeepCopyInto(out *OdooInstanceSpec) {
	*out = *in
	in.Capacity.DeepCopyInto(&out.Capacity)
	if in.Unschedulable != nil {
		in, out := &in.Unschedulable, &out.Unschedulable
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OdooInstanceSpec.
func (in *OdooInstanceSpec) DeepCopy() *OdooInstanceSpec {
	if in == nil {
		return nil
	}
	out := new(OdooInstanceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OdooInstanceStatus) DeepCopyInto(out *OdooInstanceStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OdooInstanceStatus.
func (in *OdooInstanceStatus) DeepCopy() *OdooInstanceStatus {
	if in == nil {
		return nil
	}
	out := new(OdooInstanceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OdooRehearsal) DeepCopyInto(out *OdooRehearsal) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OdooRehearsal.
func (in *OdooRehearsal) DeepCopy() *OdooRehearsal {
	if in == nil {
		return nil
	}
	out := new(OdooRehearsal)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OdooRehearsal) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OdooRehearsalList) DeepCopyInto(out *OdooRehearsalList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OdooRehearsal, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OdooRehearsalList.
func (in *OdooRehearsalList) DeepCopy() *OdooRehearsalList {
	if in == nil {
		return nil
	}
	out := new(OdooRehearsalList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OdooRehearsalList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OdooRehearsalSpec) DeepCopyInto(out *OdooRehearsalSpec) {
	*out = *in
	in.Snapshot.DeepCopyInto(&out.Snapshot)
	in.Addons.DeepCopyInto(&out.Addons)
	out.Database = in.Database
	in.Migration.DeepCopyInto(&out.Migration)
	in.Assertions.DeepCopyInto(&out.Assertions)
	if in.Budget != nil {
		in, out := &in.Budget, &out.Budget
		*out = new(Budget)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OdooRehearsalSpec.
func (in *OdooRehearsalSpec) DeepCopy() *OdooRehearsalSpec {
	if in == nil {
		return nil
	}
	out := new(OdooRehearsalSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OdooRehearsalStatus) DeepCopyInto(out *OdooRehearsalStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.UpgradeDuration != nil {
		in, out := &in.UpgradeDuration, &out.UpgradeDuration
		*out = new(v1.Duration)
		**out = **in
	}
	if in.StartedAt != nil {
		in, out := &in.StartedAt, &out.StartedAt
		*out = (*in).DeepCopy()
	}
	if in.FinishedAt != nil {
		in, out := &in.FinishedAt, &out.FinishedAt
		*out = (*in).DeepCopy()
	}
	if in.ModelCounts != nil {
		in, out := &in.ModelCounts, &out.ModelCounts
		*out = make([]ModelCountResult, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OdooRehearsalStatus.
func (in *OdooRehearsalStatus) DeepCopy() *OdooRehearsalStatus {
	if in == nil {
		return nil
	}
	out := new(OdooRehearsalStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OdooSnapshot) DeepCopyInto(out *OdooSnapshot) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OdooSnapshot.
func (in *OdooSnapshot) DeepCopy() *OdooSnapshot {
	if in == nil {
		return nil
	}
	out := new(OdooSnapshot)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OdooSnapshot) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OdooSnapshotList) DeepCopyInto(out *OdooSnapshotList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OdooSnapshot, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OdooSnapshotList.
func (in *OdooSnapshotList) DeepCopy() *OdooSnapshotList {
	if in == nil {
		return nil
	}
	out := new(OdooSnapshotList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OdooSnapshotList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OdooSnapshotSpec) DeepCopyInto(out *OdooSnapshotSpec) {
	*out = *in
	in.Source.DeepCopyInto(&out.Source)
	out.Work = in.Work
	if in.Neutralize != nil {
		in, out := &in.Neutralize, &out.Neutralize
		*out = new(bool)
		**out = **in
	}
	in.Truncate.DeepCopyInto(&out.Truncate)
	in.Mask.DeepCopyInto(&out.Mask)
	if in.Subset != nil {
		in, out := &in.Subset, &out.Subset
		*out = new(SubsetSpec)
		(*in).DeepCopyInto(*out)
	}
	in.To.DeepCopyInto(&out.To)
	if in.DenyEgress != nil {
		in, out := &in.DenyEgress, &out.DenyEgress
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OdooSnapshotSpec.
func (in *OdooSnapshotSpec) DeepCopy() *OdooSnapshotSpec {
	if in == nil {
		return nil
	}
	out := new(OdooSnapshotSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OdooSnapshotStatus) DeepCopyInto(out *OdooSnapshotStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastSuccessfulTime != nil {
		in, out := &in.LastSuccessfulTime, &out.LastSuccessfulTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OdooSnapshotStatus.
func (in *OdooSnapshotStatus) DeepCopy() *OdooSnapshotStatus {
	if in == nil {
		return nil
	}
	out := new(OdooSnapshotStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OdooTenant) DeepCopyInto(out *OdooTenant) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OdooTenant.
func (in *OdooTenant) DeepCopy() *OdooTenant {
	if in == nil {
		return nil
	}
	out := new(OdooTenant)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OdooTenant) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OdooTenantList) DeepCopyInto(out *OdooTenantList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OdooTenant, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OdooTenantList.
func (in *OdooTenantList) DeepCopy() *OdooTenantList {
	if in == nil {
		return nil
	}
	out := new(OdooTenantList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OdooTenantList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OdooTenantSpec) DeepCopyInto(out *OdooTenantSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OdooTenantSpec.
func (in *OdooTenantSpec) DeepCopy() *OdooTenantSpec {
	if in == nil {
		return nil
	}
	out := new(OdooTenantSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OdooTenantStatus) DeepCopyInto(out *OdooTenantStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OdooTenantStatus.
func (in *OdooTenantStatus) DeepCopy() *OdooTenantStatus {
	if in == nil {
		return nil
	}
	out := new(OdooTenantStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlacementCandidate) DeepCopyInto(out *PlacementCandidate) {
	*out = *in
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlacementCandidate.
func (in *PlacementCandidate) DeepCopy() *PlacementCandidate {
	if in == nil {
		return nil
	}
	out := new(PlacementCandidate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RunboatActionRequest) DeepCopyInto(out *RunboatActionRequest) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RunboatActionRequest.
func (in *RunboatActionRequest) DeepCopy() *RunboatActionRequest {
	if in == nil {
		return nil
	}
	out := new(RunboatActionRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RunboatActionResult) DeepCopyInto(out *RunboatActionResult) {
	*out = *in
	if in.ExecutedAt != nil {
		in, out := &in.ExecutedAt, &out.ExecutedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RunboatActionResult.
func (in *RunboatActionResult) DeepCopy() *RunboatActionResult {
	if in == nil {
		return nil
	}
	out := new(RunboatActionResult)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RunboatAuth) DeepCopyInto(out *RunboatAuth) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RunboatAuth.
func (in *RunboatAuth) DeepCopy() *RunboatAuth {
	if in == nil {
		return nil
	}
	out := new(RunboatAuth)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RunboatBuild) DeepCopyInto(out *RunboatBuild) {
	*out = *in
	if in.PR != nil {
		in, out := &in.PR, &out.PR
		*out = new(int32)
		**out = **in
	}
	if in.Created != nil {
		in, out := &in.Created, &out.Created
		*out = (*in).DeepCopy()
	}
	if in.LastScaled != nil {
		in, out := &in.LastScaled, &out.LastScaled
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RunboatBuild.
func (in *RunboatBuild) DeepCopy() *RunboatBuild {
	if in == nil {
		return nil
	}
	out := new(RunboatBuild)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RunboatFilter) DeepCopyInto(out *RunboatFilter) {
	*out = *in
	if in.Repos != nil {
		in, out := &in.Repos, &out.Repos
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RunboatFilter.
func (in *RunboatFilter) DeepCopy() *RunboatFilter {
	if in == nil {
		return nil
	}
	out := new(RunboatFilter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RunboatLink) DeepCopyInto(out *RunboatLink) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RunboatLink.
func (in *RunboatLink) DeepCopy() *RunboatLink {
	if in == nil {
		return nil
	}
	out := new(RunboatLink)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RunboatLink) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RunboatLinkList) DeepCopyInto(out *RunboatLinkList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RunboatLink, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RunboatLinkList.
func (in *RunboatLinkList) DeepCopy() *RunboatLinkList {
	if in == nil {
		return nil
	}
	out := new(RunboatLinkList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RunboatLinkList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RunboatLinkSpec) DeepCopyInto(out *RunboatLinkSpec) {
	*out = *in
	if in.Auth != nil {
		in, out := &in.Auth, &out.Auth
		*out = new(RunboatAuth)
		**out = **in
	}
	if in.PollInterval != nil {
		in, out := &in.PollInterval, &out.PollInterval
		*out = new(v1.Duration)
		**out = **in
	}
	if in.Filter != nil {
		in, out := &in.Filter, &out.Filter
		*out = new(RunboatFilter)
		(*in).DeepCopyInto(*out)
	}
	if in.AllowedActions != nil {
		in, out := &in.AllowedActions, &out.AllowedActions
		*out = make([]RunboatAction, len(*in))
		copy(*out, *in)
	}
	if in.ActionRequests != nil {
		in, out := &in.ActionRequests, &out.ActionRequests
		*out = make([]RunboatActionRequest, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RunboatLinkSpec.
func (in *RunboatLinkSpec) DeepCopy() *RunboatLinkSpec {
	if in == nil {
		return nil
	}
	out := new(RunboatLinkSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RunboatLinkStatus) DeepCopyInto(out *RunboatLinkStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Builds != nil {
		in, out := &in.Builds, &out.Builds
		*out = make([]RunboatBuild, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastPoll != nil {
		in, out := &in.LastPoll, &out.LastPoll
		*out = (*in).DeepCopy()
	}
	if in.ExecutedActions != nil {
		in, out := &in.ExecutedActions, &out.ExecutedActions
		*out = make([]RunboatActionResult, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RunboatLinkStatus.
func (in *RunboatLinkStatus) DeepCopy() *RunboatLinkStatus {
	if in == nil {
		return nil
	}
	out := new(RunboatLinkStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SnapshotDestination) DeepCopyInto(out *SnapshotDestination) {
	*out = *in
	if in.Volume != nil {
		in, out := &in.Volume, &out.Volume
		*out = new(VolumeProvider)
		**out = **in
	}
	if in.ObjectStore != nil {
		in, out := &in.ObjectStore, &out.ObjectStore
		*out = new(ObjectStoreProvider)
		(*in).DeepCopyInto(*out)
	}
	if in.Custom != nil {
		in, out := &in.Custom, &out.Custom
		*out = new(CustomProvider)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SnapshotDestination.
func (in *SnapshotDestination) DeepCopy() *SnapshotDestination {
	if in == nil {
		return nil
	}
	out := new(SnapshotDestination)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SnapshotProvider) DeepCopyInto(out *SnapshotProvider) {
	*out = *in
	if in.Volume != nil {
		in, out := &in.Volume, &out.Volume
		*out = new(VolumeProvider)
		**out = **in
	}
	if in.ObjectStore != nil {
		in, out := &in.ObjectStore, &out.ObjectStore
		*out = new(ObjectStoreProvider)
		(*in).DeepCopyInto(*out)
	}
	if in.HTTP != nil {
		in, out := &in.HTTP, &out.HTTP
		*out = new(HTTPProvider)
		**out = **in
	}
	if in.Custom != nil {
		in, out := &in.Custom, &out.Custom
		*out = new(CustomProvider)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SnapshotProvider.
func (in *SnapshotProvider) DeepCopy() *SnapshotProvider {
	if in == nil {
		return nil
	}
	out := new(SnapshotProvider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SnapshotSpec) DeepCopyInto(out *SnapshotSpec) {
	*out = *in
	in.From.DeepCopyInto(&out.From)
	if in.Neutralize != nil {
		in, out := &in.Neutralize, &out.Neutralize
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SnapshotSpec.
func (in *SnapshotSpec) DeepCopy() *SnapshotSpec {
	if in == nil {
		return nil
	}
	out := new(SnapshotSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SourceDatabase) DeepCopyInto(out *SourceDatabase) {
	*out = *in
	if in.Live != nil {
		in, out := &in.Live, &out.Live
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SourceDatabase.
func (in *SourceDatabase) DeepCopy() *SourceDatabase {
	if in == nil {
		return nil
	}
	out := new(SourceDatabase)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubsetSpec) DeepCopyInto(out *SubsetSpec) {
	*out = *in
	if in.Companies != nil {
		in, out := &in.Companies, &out.Companies
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.KeepGlobal != nil {
		in, out := &in.KeepGlobal, &out.KeepGlobal
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubsetSpec.
func (in *SubsetSpec) DeepCopy() *SubsetSpec {
	if in == nil {
		return nil
	}
	out := new(SubsetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TenantCompany) DeepCopyInto(out *TenantCompany) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TenantCompany.
func (in *TenantCompany) DeepCopy() *TenantCompany {
	if in == nil {
		return nil
	}
	out := new(TenantCompany)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TruncateSpec) DeepCopyInto(out *TruncateSpec) {
	*out = *in
	if in.Preset != nil {
		in, out := &in.Preset, &out.Preset
		*out = new(bool)
		**out = **in
	}
	if in.Extra != nil {
		in, out := &in.Extra, &out.Extra
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Keep != nil {
		in, out := &in.Keep, &out.Keep
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TruncateSpec.
func (in *TruncateSpec) DeepCopy() *TruncateSpec {
	if in == nil {
		return nil
	}
	out := new(TruncateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VolumeProvider) DeepCopyInto(out *VolumeProvider) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VolumeProvider.
func (in *VolumeProvider) DeepCopy() *VolumeProvider {
	if in == nil {
		return nil
	}
	out := new(VolumeProvider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkDatabase) DeepCopyInto(out *WorkDatabase) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkDatabase.
func (in *WorkDatabase) DeepCopy() *WorkDatabase {
	if in == nil {
		return nil
	}
	out := new(WorkDatabase)
	in.DeepCopyInto(out)
	return out
}
