#!/usr/bin/env python3
# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2026 Antoni Romera
#
# Forty customers and about two hundred environments, printed as YAML.
#
# This exists because a measurement decided a product question. With this fixture
# loaded, every page of the console answered in under a second, and that is the
# reason decision 5's cache has not been built: a database that can disagree with
# the cluster is not worth adding until something is slow. That measurement lived
# in a note, and a number in a note is one refactor away from having quietly
# stopped being true — the overview had already regressed once, to 215 cards and
# 127KB, inside the same day.
#
# Nothing here boots. Every environment is Hibernating or Ephemeral and no
# Postgres is created for them: the question this fixture answers is how the
# interface behaves with a lot of OBJECTS in front of it, and forty running Odoo
# instances would answer a different question on hardware nobody has.
import unicodedata

NAMES = [
    "Aceros", "Bodegas", "Cerámicas", "Distribuciones", "Envases", "Ferretería",
    "Gráficas", "Herrajes", "Iluminación", "Jardinería", "Laboratorios",
    "Maderas", "Neumáticos", "Óptica", "Papelería", "Químicas", "Rodamientos",
    "Suministros", "Textiles", "Uniformes",
]
SUFFIX = ["Norte", "Levante", "Sur"]
PURPOSES = ["Production", "Staging", "Review", "Review", "QA"]

print("""# Generated by hack/demo/scale.py. Not committed as YAML on purpose: two
# thousand lines of near-identical objects in a repository is a file nobody reads
# and everybody diffs.""")

for i in range(40):
    # Accents stripped properly and not with a couple of str.replace calls: the
    # first version handled á and ó, and the API server refused every customer
    # whose name happened to contain í or é — a lowercase RFC 1123 name has no
    # accents at all, so removing two of the five was the same as removing none.
    plain = "".join(c for c in unicodedata.normalize("NFD", NAMES[i % len(NAMES)].lower())
                    if unicodedata.category(c) != "Mn")
    name = f"c{i:02d}-{plain}"
    display = f"{NAMES[i % len(NAMES)]} {SUFFIX[i % len(SUFFIX)]}"
    print(f"""---
apiVersion: doblura.dev/v1alpha1
kind: OdooTenant
metadata: {{name: {name}, namespace: escala}}
spec:
  displayName: {display}
  domain: {name}.example
  odooVersion: "18.0"
  maxEphemeralEnvironments: 5
  images:
    - {{name: base-18, image: 'doblura/odoo:18.0', odooVersion: '18.0', default: true}}
  environmentDefaults:
    database: {{host: pg, user: odoo, passwordSecret: pg-app}}
    storage: {{filestore: {{mode: Database}}}}
    size: small""")

    # Five environments each, minus a couple on some customers so the numbers are
    # not suspiciously even: a fixture where every customer is identical hides the
    # layout problems that only appear when a row is longer than its neighbours.
    for e, purpose in enumerate(PURPOSES[: 5 - (i % 3)]):
        ephemeral = purpose in ("Review", "QA")
        life = "{type: Ephemeral, ttl: 72h}" if ephemeral else "{type: Hibernating}"
        data = "Live" if purpose == "Production" else "Demo"
        # Production may not hibernate — it is the customer's Odoo — so the one
        # Production environment per customer is Persistent and simply never
        # given an image that exists on the node.
        if purpose == "Production":
            life = "{type: Persistent}"
        print(f"""---
apiVersion: doblura.dev/v1alpha1
kind: OdooEnvironment
metadata: {{name: {name}-{purpose.lower()}-{e}, namespace: escala}}
spec:
  forTenant: {name}
  purpose: {purpose}
  imageRef: base-18
  data: {{type: {data}}}
  lifecycle: {life}
  database: {{host: pg, port: 5432, user: odoo, passwordSecret: pg-app}}
  storage: {{filestore: {{mode: Database}}}}
  size: small""")
